name: Reproduce Signal Loss Issue

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: Download DynamoRIO
        run: |
          wget https://github.com/DynamoRIO/dynamorio/releases/download/release_6_0_0/DynamoRIO-Linux-6.0.0-6.tar.gz
          tar -xzf DynamoRIO-Linux-6.0.0-6tar.gz
          export DYNAMORIO_HOME=$PWD/DynamoRIO-Linux-10.93.19944
          export PATH=$PATH:$DYNAMORIO_HOME/bin64
      - name: Build the test program
        run: |
          mkdir build
          cd build
          # Compile the test program
          g++ -o signal_test ../signal_test.cpp -lpthread

      - name: Run test program with DynamoRIO
        run: |
          # Run the test program multiple times to reproduce the signal loss issue
          for i in {1..100}; do
            echo "Run $i"
            ./DynamoRIO-Linux-6.0.0-6/bin64/drrun -- ./signal_test || echo "Signal lost on run $i"
          done
