name: Reproduce Signal Loss Issue

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: Download DynamoRIO
        run: |
          wget https://github.com/DynamoRIO/dynamorio/releases/download/release_6_0_0/DynamoRIO-Linux-6.0.0-6.tar.gz
          tar -xzf DynamoRIO-Linux-6.0.0-6.tar.gz
          # wget https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-10.91.19860/DynamoRIO-Linux-10.91.19860.tar.gz
          # tar -xzf DynamoRIO-Linux-10.91.19860.tar.gz
      - name: Disable Address Space Randomization
        if: runner.os == 'Linux'
        run: sudo sysctl -w kernel.randomize_va_space=0
      
      - name: Disable swapping 
        if: runner.os == 'Linux' 
        run: sudo swapoff -a

      - name: Build the test program
        run: |
          ls -l
          mkdir build
          cd build
          # Compile the test program
          g++ -o signal_test ../signal_test.cpp -lpthread
          ls -l

      - name: Run test program with DynamoRIO
        run: |
          set +e
          # Run the test program multiple times to reproduce the signal loss issue
          for i in {1..100}; do
            echo "Run $i"
            # ./DynamoRIO-Linux-10.91.19860/bin64/drrun -- ./build/signal_test || echo "Signal lost on run $i"
            ./DynamoRIO-Linux-6.0.0-6/bin64/drrun -- ./build/signal_test || echo "Signal lost on run $i"
          done
